In [2]:
import os
import numpy as np
import pandas as pd
from itertools import islice
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [3]:
text = '''The atmosphere at the stadium was electric, a sea of blue jerseys and flags creating a wave of support for the Indian cricket team. 
It was the World Cup final, and India was playing against their long-time rivals. The match had been a rollercoaster of emotions, with both teams displaying exceptional skill and determination.
As the final over began, India needed just 15 runs to win, with two wickets in hand. The stadium roared with anticipation and anxiety. At the crease was Rohan Singh, India's young sensation, known for his aggressive batting style. Beside him was veteran player Arjun Patel, calm and composed, ready to support the team in these crucial moments.
The opposing team's bowler, a renowned fast bowler, took his run-up, and the crowd held its breath. The first ball was a yorker, aimed perfectly at the stumps, but Rohan skillfully drove it away for two runs. The next ball was a bouncer, which Rohan managed to dodge skillfully. The tension was palpable as the third ball approached.
This time, the bowler tried a slower ball, but Rohan was ready. With a powerful swing, he sent the ball soaring over the boundary for a six! The crowd erupted in cheers, the Indian flags waving more vigorously than ever. Only seven runs were now needed from three balls.
The fourth ball was a tight one, leading to a quick single. Arjun, now on strike, faced the pressure. He played a strategic shot, placing the ball into the gap for two runs. The scoreboard now read that four runs were needed off the last two balls.
The penultimate ball was a crucial moment. Arjun, with years of experience, read the bowler's mind and pre-empted a full-length delivery. He stepped out, making perfect contact, and the ball raced towards the boundary. The crowd was on their feet, shouting and cheering, as the ball crossed the boundary line.
India had won the World Cup! The players rushed onto the field, hugging and lifting each other in joyous celebration. Fireworks lit up the sky, and the sounds of drums and cheers filled the air. Rohan and Arjun were hoisted on their teammates' shoulders, heroes of a nation united by the love of cricket.'''

In [4]:
mytokenizer = Tokenizer()
mytokenizer.fit_on_texts([text])
total_words = len(mytokenizer.word_index) + 1

In [5]:
total_words

209

In [6]:
mytokenizer

In [7]:
def take(n, iterable):
    """Return the first n items of the iterable as a list."""
    return list(islice(iterable, n))

In [8]:
take(50, mytokenizer.word_index.items())

[('the', 1),
 ('a', 2),
 ('and', 3),
 ('was', 4),
 ('ball', 5),
 ('of', 6),
 ('for', 7),
 ('with', 8),
 ('runs', 9),
 ('rohan', 10),
 ('to', 11),
 ('two', 12),
 ('in', 13),
 ('arjun', 14),
 ('at', 15),
 ('india', 16),
 ('their', 17),
 ('as', 18),
 ('needed', 19),
 ('bowler', 20),
 ('crowd', 21),
 ('he', 22),
 ('boundary', 23),
 ('were', 24),
 ('now', 25),
 ('on', 26),
 ('stadium', 27),
 ('flags', 28),
 ('support', 29),
 ('indian', 30),
 ('cricket', 31),
 ('team', 32),
 ('it', 33),
 ('world', 34),
 ('cup', 35),
 ('final', 36),
 ('time', 37),
 ('had', 38),
 ('over', 39),
 ('his', 40),
 ('ready', 41),
 ('crucial', 42),
 ('up', 43),
 ('but', 44),
 ('skillfully', 45),
 ('cheers', 46),
 ('balls', 47),
 ('read', 48),
 ('atmosphere', 49),
 ('electric', 50)]

In [10]:
my_input_sequences = []
for line in text.split('\n'):
    print(line, "\n")
    token_list = mytokenizer.texts_to_sequences([line])[0]
    print(token_list, "\n")
    for i in range(1, len(token_list)):
        my_n_gram_sequence = token_list[:i+1]
        print(my_n_gram_sequence)
        break
    break

The atmosphere at the stadium was electric, a sea of blue jerseys and flags creating a wave of support for the Indian cricket team.  

[1, 49, 15, 1, 27, 4, 50, 2, 51, 6, 52, 53, 3, 28, 54, 2, 55, 6, 29, 7, 1, 30, 31, 32] 

[1, 49]


In [11]:
my_input_sequences = []
for line in text.split('\n'):
    token_list = mytokenizer.texts_to_sequences([line])[0]
    print(token_list, "\n")
    for i in range(1, len(token_list)):
        my_n_gram_sequence = token_list[:i+1]
        #print(my_n_gram_sequence)
        my_input_sequences.append(my_n_gram_sequence)
        #print(input_sequences)

[1, 49, 15, 1, 27, 4, 50, 2, 51, 6, 52, 53, 3, 28, 54, 2, 55, 6, 29, 7, 1, 30, 31, 32] 

[33, 4, 1, 34, 35, 36, 3, 16, 4, 56, 57, 17, 58, 37, 59, 1, 60, 38, 61, 2, 62, 6, 63, 8, 64, 65, 66, 67, 68, 3, 69] 

[18, 1, 36, 39, 70, 16, 19, 71, 72, 9, 11, 73, 8, 12, 74, 13, 75, 1, 27, 76, 8, 77, 3, 78, 15, 1, 79, 4, 10, 80, 81, 82, 83, 84, 7, 40, 85, 86, 87, 88, 89, 4, 90, 91, 14, 92, 93, 3, 94, 41, 11, 29, 1, 32, 13, 95, 42, 96] 

[1, 97, 98, 20, 2, 99, 100, 20, 101, 40, 102, 43, 3, 1, 21, 103, 104, 105, 1, 106, 5, 4, 2, 107, 108, 109, 15, 1, 110, 44, 10, 45, 111, 33, 112, 7, 12, 9, 1, 113, 5, 4, 2, 114, 115, 10, 116, 11, 117, 45, 1, 118, 4, 119, 18, 1, 120, 5, 121] 

[122, 37, 1, 20, 123, 2, 124, 5, 44, 10, 4, 41, 8, 2, 125, 126, 22, 127, 1, 5, 128, 39, 1, 23, 7, 2, 129, 1, 21, 130, 13, 46, 1, 30, 28, 131, 132, 133, 134, 135, 136, 137, 9, 24, 25, 19, 138, 139, 47] 

[1, 140, 5, 4, 2, 141, 142, 143, 11, 2, 144, 145, 14, 25, 26, 146, 147, 1, 148, 22, 149, 2, 150, 151, 152, 1, 5, 153, 1, 154,

In [12]:
len(my_input_sequences)

366

In [13]:
for item in my_input_sequences[:30]:
    print(item)

[1, 49]
[1, 49, 15]
[1, 49, 15, 1]
[1, 49, 15, 1, 27]
[1, 49, 15, 1, 27, 4]
[1, 49, 15, 1, 27, 4, 50]
[1, 49, 15, 1, 27, 4, 50, 2]
[1, 49, 15, 1, 27, 4, 50, 2, 51]
[1, 49, 15, 1, 27, 4, 50, 2, 51, 6]
[1, 49, 15, 1, 27, 4, 50, 2, 51, 6, 52]
[1, 49, 15, 1, 27, 4, 50, 2, 51, 6, 52, 53]
[1, 49, 15, 1, 27, 4, 50, 2, 51, 6, 52, 53, 3]
[1, 49, 15, 1, 27, 4, 50, 2, 51, 6, 52, 53, 3, 28]
[1, 49, 15, 1, 27, 4, 50, 2, 51, 6, 52, 53, 3, 28, 54]
[1, 49, 15, 1, 27, 4, 50, 2, 51, 6, 52, 53, 3, 28, 54, 2]
[1, 49, 15, 1, 27, 4, 50, 2, 51, 6, 52, 53, 3, 28, 54, 2, 55]
[1, 49, 15, 1, 27, 4, 50, 2, 51, 6, 52, 53, 3, 28, 54, 2, 55, 6]
[1, 49, 15, 1, 27, 4, 50, 2, 51, 6, 52, 53, 3, 28, 54, 2, 55, 6, 29]
[1, 49, 15, 1, 27, 4, 50, 2, 51, 6, 52, 53, 3, 28, 54, 2, 55, 6, 29, 7]
[1, 49, 15, 1, 27, 4, 50, 2, 51, 6, 52, 53, 3, 28, 54, 2, 55, 6, 29, 7, 1]
[1, 49, 15, 1, 27, 4, 50, 2, 51, 6, 52, 53, 3, 28, 54, 2, 55, 6, 29, 7, 1, 30]
[1, 49, 15, 1, 27, 4, 50, 2, 51, 6, 52, 53, 3, 28, 54, 2, 55, 6, 29, 7, 1, 30, 31]


In [14]:
max_sequence_len = max([len(seq) for seq in my_input_sequences])
input_sequences = np.array(pad_sequences(my_input_sequences, maxlen=max_sequence_len, padding='pre'))

In [15]:
max_sequence_len

59

In [16]:
input_sequences.shape

(366, 59)

In [17]:
for item in input_sequences[:5]:
    print(item)

[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  1 49]
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  1 49 15]
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  1 49 15  1]
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  1 49 15  1 27]
[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  1 49 15  1 27  4]


In [18]:
X = input_sequences[:, :-1]
y = input_sequences[:, -1]

In [19]:
X[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=int32)

In [20]:
y[0]

49

In [21]:
X[1]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  1, 49], dtype=int32)

In [22]:
y[1]

15

# Convert target to one hot encoded vectors

In [23]:
y

array([ 49,  15,   1,  27,   4,  50,   2,  51,   6,  52,  53,   3,  28,
        54,   2,  55,   6,  29,   7,   1,  30,  31,  32,   4,   1,  34,
        35,  36,   3,  16,   4,  56,  57,  17,  58,  37,  59,   1,  60,
        38,  61,   2,  62,   6,  63,   8,  64,  65,  66,  67,  68,   3,
        69,   1,  36,  39,  70,  16,  19,  71,  72,   9,  11,  73,   8,
        12,  74,  13,  75,   1,  27,  76,   8,  77,   3,  78,  15,   1,
        79,   4,  10,  80,  81,  82,  83,  84,   7,  40,  85,  86,  87,
        88,  89,   4,  90,  91,  14,  92,  93,   3,  94,  41,  11,  29,
         1,  32,  13,  95,  42,  96,  97,  98,  20,   2,  99, 100,  20,
       101,  40, 102,  43,   3,   1,  21, 103, 104, 105,   1, 106,   5,
         4,   2, 107, 108, 109,  15,   1, 110,  44,  10,  45, 111,  33,
       112,   7,  12,   9,   1, 113,   5,   4,   2, 114, 115,  10, 116,
        11, 117,  45,   1, 118,   4, 119,  18,   1, 120,   5, 121,  37,
         1,  20, 123,   2, 124,   5,  44,  10,   4,  41,   8,   

In [24]:
total_words

209

In [25]:
y = np.array(tf.keras.utils.to_categorical(y, num_classes=total_words))
y[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.], dtype=float32)

In [26]:
model = Sequential()
model.add(Embedding(input_dim=total_words, output_dim=100, input_length=max_sequence_len-1))
model.add(LSTM(units = 150))
model.add(Dense(units = total_words, activation='softmax'))
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 58, 100)           20900     
                                                                 
 lstm (LSTM)                 (None, 150)               150600    
                                                                 
 dense (Dense)               (None, 209)               31559     
                                                                 
Total params: 203059 (793.20 KB)
Trainable params: 203059 (793.20 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [1]:
# No. of parameters in Embedding layer is equal to no. of dimensions x vocab size
# vocab_size = 209
# No. of dimensions = 100
# Params = 209x100 = 20900
# 
# No. of params in LSTM = 4×(units×(input_dim+units+1))
# units is the number of LSTM units in the layer.
# input_dim is the dimensionality of the input to the LSTM layer.
# 
# No. of params in LSTM = 4 x (150 x (100 + 150 + 1))
#                       = 4 x (150 x 251)
#                       = 4 x 37650
#                       = 150600
#                       
# Number of Parameters in Dense layer = (input_units+1)×output_units
#                                     = (150 + 1)x209
#                                     = 151 x 209
#                                     = 31,559
#                                     

In [27]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=100, verbose=1)

Epoch 1/100
12/12 [==============================] - 3s 69ms/step - loss: 5.3343 - accuracy: 0.0765
Epoch 2/100
12/12 [==============================] - 1s 67ms/step - loss: 5.1130 - accuracy: 0.1011
Epoch 3/100
12/12 [==============================] - 1s 68ms/step - loss: 4.9239 - accuracy: 0.1011
Epoch 4/100
12/12 [==============================] - 1s 68ms/step - loss: 4.8766 - accuracy: 0.1011
Epoch 5/100
12/12 [==============================] - 1s 71ms/step - loss: 4.8495 - accuracy: 0.1011
Epoch 6/100
12/12 [==============================] - 1s 68ms/step - loss: 4.8431 - accuracy: 0.1011
Epoch 7/100
12/12 [==============================] - 1s 67ms/step - loss: 4.8269 - accuracy: 0.1011
Epoch 8/100
12/12 [==============================] - 1s 68ms/step - loss: 4.8054 - accuracy: 0.1011
Epoch 9/100
12/12 [==============================] - 1s 66ms/step - loss: 4.7815 - accuracy: 0.1011
Epoch 10/100
12/12 [==============================] - 1s 68ms/step - loss: 4.7444 - accuracy: 0.1011

In [28]:
input_text = "India needed"
predict_next_words= 10

for _ in range(predict_next_words):
    token_list = mytokenizer.texts_to_sequences([input_text])[0]
    print(token_list)
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
    predicted = np.argmax(model.predict(token_list), axis=-1)
    output_word = ""
    for word, index in mytokenizer.word_index.items():
        if index == predicted:
            output_word = word
            break
    input_text += " " + output_word

print(input_text)

[16, 19]
1/1 [==============================] - 0s 497ms/step
[16, 19, 71]
1/1 [==============================] - 0s 24ms/step
[16, 19, 71, 72]
1/1 [==============================] - 0s 25ms/step
[16, 19, 71, 72, 9]
1/1 [==============================] - 0s 25ms/step
[16, 19, 71, 72, 9, 1]
1/1 [==============================] - 0s 25ms/step
[16, 19, 71, 72, 9, 1, 20]
1/1 [==============================] - 0s 27ms/step
[16, 19, 71, 72, 9, 1, 20, 2]
1/1 [==============================] - 0s 25ms/step
[16, 19, 71, 72, 9, 1, 20, 2, 62]
1/1 [==============================] - 0s 26ms/step
[16, 19, 71, 72, 9, 1, 20, 2, 62, 6]
1/1 [==============================] - 0s 28ms/step
[16, 19, 71, 72, 9, 1, 20, 2, 62, 6, 63]
1/1 [==============================] - 0s 26ms/step
India needed just 15 runs the bowler a rollercoaster of emotions with
